### ISSUE TITLE
Why not use this on NixOS

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [balsoft/nixos-fhs-compat#2]
Hey this library looks really cool. I'm curious why it shouldn't be used on NixOS. It seems like it could offer a smoother transition for people coming from a more traditional Linux distribution.

**Comment by balsoft** [comment]
This ruins reproducibility -- it creates a lot of ways for stuff to work for you but not for others.

**Comment by Th3Whit3Wolf** [comment]
> This ruins reproducibility

That's true but for people ripping their hair out trying to figure out what dependency is causing their program not compile/run this would probably be welcomed.

I'm not very familiar with `strace` but I would imagine that there are circumstances where someone could use your library to temporarily make their program work and run strace to see what the runtime dependencies were missing.

I think the warning might be a bit too strong given it won't break their system.

Maybe it could be rewritten to

## :warning: This library is only intended to be used in containers! Usage on NixOS host may result in irreproducibility!

**Comment by balsoft** [comment]
I think this is reasonable, thanks!

**Comment by YodaEmbedding** [comment]
Would disabling this when building for nixpkgs and then reenabling it afterwards ensure reproducibility is preserved?

**Comment by balsoft** [comment]
TBH I'm not sure when exactly systemd cleans up the tmpfiles. I think disabling the module, running `sudo nixos-rebuild switch` and then `sudo systemd-tmpfiles --clean` should give you the clean system back.

**Comment by tmarkov** [comment]
Would this work with a setup that wipes `/` on boot? And would such a setup alleviate the issues with it?

**Comment by Th3Whit3Wolf** [comment]
@tmarkov I used it on a system that mounts `/` on `tmpfs` without issue.
